name: genetic-algorithm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyqt
  - tk
  - pip:
      - opfunu
      - benchmark-functions

